print("Persona: ¡Hola, Gatito!")
print("Gato: Miau... ¡Hola humano!")
print("Persona: ¿Dormiste bien?")
print("Gato: Dormí sobre tu ropa limpia, asi que si, bastante bien.")
print("Persona: ¡Otra vez! Esa ropa estaba recien lavada.")
print("Gato: Lo se. Es mas comoda que mi cama.")
print("Persona: ¿Tienes hambre?")
print("Gato: Solo si traes un raton o atun.")
print("Persona: No tengo ratones, pero si croquetas.")
print("Gato: Mmm... no es lo que esperaba, pero esta bien.")
print("Persona: ¿Que hiciste mientras no estaba?")
print("Gato: Derribe una planta. Fue divertido.")
print("Persona: ¡Gatito! Esa planta era nueva.")
print("Gato: No me gustaba donde estaba, la movi por ti.")
print("Persona: Eres un desastre... pero te quiero.")
print("Gato: Miau, yo también, humano raro.")
print("Persona: Bueno, hora de descansar.")
print("Gato: Esta bien, pero dormiré sobre tu almohada.")
print("Persona: ¡Gatitooo!")
print("Gato: Miau, buenas noches.")
